{"name": "Delete a pet from the store", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: 32 still exists\nassert 404 == 200\n +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D173C10>>('/pet/', '32')\n +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D173C10>> = <api_create.ApiPet object at 0x000002593D173C10>.delete_by_id\n +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D1030>.get_id_url\n +    and   '32' = str(32)", "trace": "self = <test_api.TestApiExam object at 0x000002593D0D1030>, create_pet_object = <api_create.ApiPet object at 0x000002593D173C10>, _id = 32\n\n    @allure.title(\"Delete a pet from the store\")\n    @allure.description(\"Check relevant response\")\n    @pytest.mark.xfail(strict=True)\n    @pytest.mark.parametrize(\"_id\", [4, 32, 34])\n    def test_delete_non_existed_pet(self, create_pet_object, _id):\n        with allure.step('Check status code'):\n>           assert create_pet_object.delete_by_id(self.get_id_url, str(_id)) == 200, f'{_id} still exists'\nE           AssertionError: 32 still exists\nE           assert 404 == 200\nE            +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D173C10>>('/pet/', '32')\nE            +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D173C10>> = <api_create.ApiPet object at 0x000002593D173C10>.delete_by_id\nE            +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D1030>.get_id_url\nE            +    and   '32' = str(32)\n\ntests\\test_api.py:86: AssertionError"}, "description": "Check relevant response", "steps": [{"name": "Check status code", "status": "failed", "statusDetails": {"message": "AssertionError: 32 still exists\nassert 404 == 200\n +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D173C10>>('/pet/', '32')\n +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D173C10>> = <api_create.ApiPet object at 0x000002593D173C10>.delete_by_id\n +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D1030>.get_id_url\n +    and   '32' = str(32)\n", "trace": "  File \"D:\\PyProjects\\homework\\pythonProject\\tests\\test_api.py\", line 86, in test_delete_non_existed_pet\n    assert create_pet_object.delete_by_id(self.get_id_url, str(_id)) == 200, f'{_id} still exists'\n"}, "start": 1703710489881, "stop": 1703710490600}], "parameters": [{"name": "_id", "value": "32"}], "start": 1703710489880, "stop": 1703710490600, "uuid": "393a5ec8-3326-4476-b4d3-b82884770a4a", "historyId": "552309f192536f922f0bbbc0d076bafa", "testCaseId": "3b38a9af0f65b31894ff5fd3280bd561", "fullName": "tests.test_api.TestApiExam#test_delete_non_existed_pet", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(strict=True)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiExam"}, {"name": "host", "value": "DESKTOP-Q0K3D1C"}, {"name": "thread", "value": "18048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}