{"name": "Delete a pet from the store", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: 4 still exists\nassert 404 == 200\n +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D1AC250>>('/pet/', '4')\n +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D1AC250>> = <api_create.ApiPet object at 0x000002593D1AC250>.delete_by_id\n +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D0EB0>.get_id_url\n +    and   '4' = str(4)", "trace": "self = <test_api.TestApiExam object at 0x000002593D0D0EB0>, create_pet_object = <api_create.ApiPet object at 0x000002593D1AC250>, _id = 4\n\n    @allure.title(\"Delete a pet from the store\")\n    @allure.description(\"Check relevant response\")\n    @pytest.mark.xfail(strict=True)\n    @pytest.mark.parametrize(\"_id\", [4, 32, 34])\n    def test_delete_non_existed_pet(self, create_pet_object, _id):\n        with allure.step('Check status code'):\n>           assert create_pet_object.delete_by_id(self.get_id_url, str(_id)) == 200, f'{_id} still exists'\nE           AssertionError: 4 still exists\nE           assert 404 == 200\nE            +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D1AC250>>('/pet/', '4')\nE            +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D1AC250>> = <api_create.ApiPet object at 0x000002593D1AC250>.delete_by_id\nE            +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D0EB0>.get_id_url\nE            +    and   '4' = str(4)\n\ntests\\test_api.py:86: AssertionError"}, "description": "Check relevant response", "steps": [{"name": "Check status code", "status": "failed", "statusDetails": {"message": "AssertionError: 4 still exists\nassert 404 == 200\n +  where 404 = <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D1AC250>>('/pet/', '4')\n +    where <bound method ApiPet.delete_by_id of <api_create.ApiPet object at 0x000002593D1AC250>> = <api_create.ApiPet object at 0x000002593D1AC250>.delete_by_id\n +    and   '/pet/' = <test_api.TestApiExam object at 0x000002593D0D0EB0>.get_id_url\n +    and   '4' = str(4)\n", "trace": "  File \"D:\\PyProjects\\homework\\pythonProject\\tests\\test_api.py\", line 86, in test_delete_non_existed_pet\n    assert create_pet_object.delete_by_id(self.get_id_url, str(_id)) == 200, f'{_id} still exists'\n"}, "start": 1703710489090, "stop": 1703710489864}], "parameters": [{"name": "_id", "value": "4"}], "start": 1703710489090, "stop": 1703710489865, "uuid": "032c27c8-d596-4c10-8951-71ead9be01f1", "historyId": "22b47243a3d4e8f635b6b0f071fd2182", "testCaseId": "3b38a9af0f65b31894ff5fd3280bd561", "fullName": "tests.test_api.TestApiExam#test_delete_non_existed_pet", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(strict=True)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApiExam"}, {"name": "host", "value": "DESKTOP-Q0K3D1C"}, {"name": "thread", "value": "18048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}